traveller/main/urls.py
from django.urls import path
from . import views

app_name = "main"  # here for namespacing of urls.

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("register/", views.register, name="register"),
    path("account/", views.account, name="account"),
    path("posts/", views.posts, name="posts"),
    path("send_post/", views.send_post, name="send_post"),
    path("delete_post/", views.delete_post, name="delete_post"),
    path("send_message/", views.send_message, name="send_message"),
    path("modify_post/", views.modify_post, name="modify_post"),
    path("upload_img/", views.upload_img, name="upload_img"),
    path("messages_posted/", views.messages_posted, name="messages_posted"),
    path("display_map/", views.display_map, name="display_map"),
    path('update_account/', views.update_account, name="update_account"),
    path("get_geocode/", views.get_geocode, name="get_geocode"),
    path("profil/", views.profil, name="profil"),
    path("delete_message/<int:message_id>/", views.delete_message, name="delete_message")
]

traveller/traveller/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.conf.urls import handler404, handler500


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('realadmin/', admin.site.urls),
]

# handler404 = 'main.views.error_404_view'

# handler500 = 'main.views.error_500_view'

traveller/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Country(models.Model):
    """
    Class used to define a country
    """

    name = models.CharField(max_length=200)
    alpha_2 = models.CharField(max_length=20)
    alpha_3 = models.CharField(max_length=20)
    temp_averges = models.CharField(max_length=500)
    flag = models.CharField(max_length=200)
    resume = models.TextField()
    picture = models.TextField()


# Create your models here.
class Post(models.Model):
    """
    Class used to define a travel place
    """

    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    creation_date = models.DateField(auto_now=True)
    city = models.CharField(max_length=200)
    total_travelers = models.DecimalField(max_digits=4, decimal_places=0)
    wanted_travelers = models.DecimalField(max_digits=4, decimal_places=0)
    free_places = models.DecimalField(max_digits=4, decimal_places=0)
    interest = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    message = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    ready = models.BooleanField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    budget = models.CharField(max_length=100)


class UserAttributes(models.Model):
    """
    Class used to edit the user profil attributes
    """

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    avatar = models.CharField(max_length=100)
    last_connexion = models.DateField()
    about = models.TextField()
    img = models.TextField(default="")


class Messages(models.Model):
    """
    Class used to store messages send
    """

    title = models.CharField(max_length=200)
    created_at = models.DateField(auto_now=True)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)

traveller/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    """Form used for general query"""

    search = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "inputForm", "placeholder": "Ex: Paris"}
        ),
        label=False,
    )


class ProfilForm(forms.Form):
    """Form used for profil infos"""

    username = forms.CharField(max_length=100)
    about = forms.Textarea()


class UserFormWithEmail(UserCreationForm):
    """Class used to register with email"""

    email = forms.EmailField(required=True)
    age = forms.DecimalField(max_digits=2, min_value=18, decimal_places=0)

    def __init__(self, *args, **kwargs):
        super(UserFormWithEmail, self).__init__(*args, **kwargs)

        for fieldname in ["username", "email", "password1", "password2"]:
            self.fields[fieldname].help_text = None

    def save(self, commit=True):
        user = super(UserFormWithEmail, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class PostForm(forms.Form):
    """ Class used to define a post """

    country = forms.CharField(max_length=200)
    city = forms.CharField(max_length=200)
    total = forms.DecimalField(max_digits=4, decimal_places=0)
    wanted = forms.DecimalField(max_digits=4, decimal_places=0)
    free = forms.DecimalField(max_digits=4, decimal_places=0)
    interest = forms.CharField(max_length=200)
    title = forms.CharField(max_length=200)
    message = forms.CharField(max_length=2000)
    start = forms.CharField(max_length=200)
    end = forms.CharField(max_length=200)
    budget = forms.CharField(max_length=100)

    def save(self, commit=True):
        """Save method to insert posts in DB """

        country = self.country.cleaned_data["country"]
        city = self.city.cleaned_data["city"]
        total = self.total.cleaned_data["total"]
        wanted = self.wanted.cleaned_data["wanted"]
        free = self.free.cleaned_data["free"]
        interest = self.interest.cleaned_data["interest"]
        title = self.title.cleaned_data["title"]
        message = self.message.cleaned_data["message"]
        start = self.start.cleaned_data["start"]
        end = self.end.cleaned_data["end"]
        budget = self.budget.cleaned_data["budget"]

        return self.country

traveller/main/views.py
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import SearchForm
from django.views.decorators.csrf import requires_csrf_token, csrf_exempt
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserFormWithEmail, PostForm, ProfilForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.views import LoginView
from .geomap import GeoMaps
import pycountry
from main.models import Country, Post, Messages, UserAttributes
from django.http import JsonResponse
from datetime import date
from django.db.models import Count
from django.core.paginator import Paginator
from operator import itemgetter
import base64
from datetime import date, datetime
import os
import json


def index(request):
    """
    This function returns the  template
    """
    user = request.user
    month = datetime.now()
    month = month.strftime("%B")
    actual_month = month[0:3]

    mssg = Messages.objects.filter(author=user.id)
    choicelist = []
    c = Country.objects.all()
    for i in c:
        choicelist.append(i)

    post_count = Country.objects.annotate(Count("post"))

    clist = list(
        post_count.values_list(
            "name",
            "flag",
            "alpha_2",
            "post__count",
            "id",
            "resume",
            "picture",
            "temp_averges",            
        )
    )

    for i in range(0, len(clist)):
        clist[i] = list(clist[i])
        clist[i][-1] = json.dumps(eval(clist[i][-1]))

    clist = sorted(clist, key=itemgetter(3),)  # sort list by index[3] (posts)
    
    paginator = Paginator(clist, 6)  # Show  6  contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "actual_month": actual_month,
        "clist": clist,
        "choicelist": choicelist,
        "page_obj": page_obj,
        "mesages": mssg,
    }

    return render(request, "main/index.html", context)


def login_request(request):
    """
    This functions is used to get the user logged if
    the Auth is auth is success
    """
    if request.user.is_authenticated:
        return redirect("/")
    else:
        if request.method == "POST":
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(request, "Logged in!")
                    return redirect("/")
                else:
                    return redirect('/')
            else:
                pass
        form = AuthenticationForm()

        return render(
            request=request,
            template_name="main/login.html",
            context={"form": form},
        )


def register(request):
    """
    This function returns the register form template
    """
    if request.method == "POST":
        form = UserFormWithEmail(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get("username")
            login(request, user)
            today = date.today()
            user_att = UserAttributes(
                owner=user, avatar="", about="", img="", last_connexion=today
            )
            user_att.save()

            return redirect("/")
        else:
            return render(
                request=request,
                template_name="main/register.html",
                context={"form": form},
            )

    form = UserFormWithEmail
    return render(
        request=request,
        template_name="main/register.html",
        context={"form": form},
    )


def logout_request(request):
    """
    This function is used by the user to logout
    """
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "Logged out!")
        return redirect("main:index")
    else:
        return redirect("main:index")


def account(request):
    if request.user.is_authenticated:
        img = UserAttributes.objects.filter(owner=request.user).latest(
            "id"
        )
        img = img.img
        infos = UserAttributes.objects.filter(owner=request.user).latest("id")
        name = request.user.username
        email = request.user.email
        context = {"name": name, "email": email, "img": img, "infos": infos}
        return render(request, "main/account.html", context)
    else:
        return redirect("/")


def posts(request):
    if request.method == "GET":
        country_id = request.GET.get("country_id")
        api_key = os.environ.get("FRONT_API_KEY")
        clist = []
        c = Country.objects.all()
        for i in c:
            clist.append(i)
        try:
            c = Country.objects.get(id=country_id)
        except ValueError:
            return redirect("/")
        except ObjectDoesNotExist:
            return redirect("/")
        alpha = c.alpha_2
        name = c.name

        url = f"../static/img/flags/flag-{alpha}.jpg"
        user = request.user
        messages = Messages.objects.all()
        all_posts = Post.objects.filter(country__id=c.id)
        poster_pictures = {}
        for i in all_posts:
            user_instance = User.objects.get(username=i.created_by)
            try:
                user_attribut = UserAttributes.objects.filter(
                    owner=user_instance
                ).latest("id")
                poster_pictures[i.created_by] = user_attribut.img
            except:
                poster_pictures[i.created_by] = ""

        context = {
            "poster_pictures": poster_pictures,
            "messages": messages,
            "url": url,
            "user": user,
            "form": "form",
            "clist": clist,
            "name": name,
            "country_id": country_id,
            "all_posts": all_posts,
            "api_key": api_key,
        }

    return render(request, f"main/posts.html", context)


def send_post(request):
    if request.user.is_authenticated:
        form = PostForm(request.POST)
        if request.method == "POST":
            form = PostForm(request.POST)
            if form.is_valid():
                country = Country.objects.get(
                    name=form.cleaned_data["country"]
                )

                new_post = Post(
                    country=country,
                    city=form.cleaned_data["city"],
                    total_travelers=form.cleaned_data["total"],
                    wanted_travelers=form.cleaned_data["wanted"],
                    free_places=form.cleaned_data["free"],
                    interest=form.cleaned_data["interest"],
                    title=form.cleaned_data["title"],
                    message=form.cleaned_data["message"],
                    start_date=form.cleaned_data["start"],
                    end_date=form.cleaned_data["end"],
                    budget=form.cleaned_data["budget"],
                    ready=False,
                    created_by=request.user,
                )
                new_post.save()

                clist = []
                c = Country.objects.all()
                for i in c:
                    clist.append(i)
                all_posts = Post.objects.filter(country__id=country.id)
                alpha = country.alpha_2
                url = f"../static/img/flags/flag-{alpha}.jpg"
                name = country.name
                mess = "Message sent!"
                context = {
                    "all_posts": all_posts,
                    "clist": clist,
                    "url": url,
                    "name": name,
                    "mess": mess,
                }
                messages.success(request, "Post sent!")
                return render(request, "main/posts.html", context)
            else:
                return redirect("/")
        else:
            return redirect("/")
    else:
        return render(request, "main/posts.html")


@requires_csrf_token
def delete_post(request) -> dict:
    if request.user.is_authenticated:
        try:
            post_id = request.POST["post_id"]
            selected_post = Post.objects.get(id=post_id)
            selected_post.delete()
            return JsonResponse({"result": "deleted"})
        except ValueError:
            return JsonResponse({"result": "failed"})
    else:
        return redirect("/")


@requires_csrf_token
def send_message(request) -> dict:
    """
    Function used to send message
    """
    if request.user.is_authenticated:        
        content = request.POST.get("message")
        author = request.user
        post_ref = request.POST.get("post_ref")
        post_id = Post.objects.get(id=post_ref)
        Messages.objects.create(
            title="", content=content, author=author, post_id=post_id
        )
        return JsonResponse({"message": "SEND OK"})
    return JsonResponse({"failed": "failed"})


@requires_csrf_token
def modify_post(request) -> dict:
    """
    Function defined to modify a specific post
    """
    if request.user.is_authenticated:
        if request.is_ajax():
            post_id = request.POST["post_id"]
            post = Post.objects.filter(id=post_id).values()
            post = post[0]

            context = {
                "post": post,
            }
            return JsonResponse(context)
    else:
        return redirect("/")


@requires_csrf_token
def upload_img(request) -> dict:
    """
    Function defined to upload profile image
    """

traveller/main/templates/main/includes/login-form.html
{% block content %}
{% load static %} {% load crispy_forms_tags%}
<link rel="stylesheet" type="text/css" href="{% static '/css/login-form.css'%}">

{% load bootstrap4 %}
<header class="masthead">
    <div class="container h-100 mt-5">
      <div class="row h-100 align-items-center justify-content-center text-center">
        {# Display a form #}
        <div class='row justify-content-center' >
          <div class="col-12">
             <div class="card">
               <div class="card-body">
                <form method="post" class="form" style="color: #343a40;">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-warning btn-block">submit</button>
                {% endbuttons %}
                Dont have an account yet? <a href="/register"><strong>Create one</strong></a>.
                </form>
              </div>
            </div>
          </div>
          </div>
      </div>
    </div>
  </header>
{% endblock %}

traveller/main/templates/main/includes/message.html
{% load static%}
{% block message %}

<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">          
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text" name="message" required></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id='new-message'>Send message</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

traveller/main/templates/main/includes/navbar.html
{% block content %}
 {% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  {% if user.is_authenticated%}
  <a class="navbar-brand text-warning" href="/" style="font-family:Chelsea Market, cursive;'">Travelerer Helper</a>
  {%else%}
  <a class="navbar-brand" href="/" style="font-family:Chelsea Market, cursive;'" data-aos="fade-right">Travelerer Helper</a>
  {%endif%}

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" data-aos="fade-left">
    <ul class="navbar-nav mr-auto">
    </ul>
    {% if user.is_authenticated%}
    {% if messages != '' %}
    <a class="nav-link text-warning" href="{% url 'main:messages_posted' %}" style='color:white'> Messages</a>    
    {% endif %}
    <a class="nav-link text-warning" href="{% url 'main:account' %}" id="login_button" style='color:white' > My account</a>
    <a class="nav-link text-warning" href="{% url 'main:logout' %}" id="logout_button"style='color:white' > Logout</a>
    {% else %}
    <a class="nav-link text-warning" href="{% url 'main:login' %}" style='color:white'
      style="font-family:Chelsea Market, cursive;'">Login</a>
    <a class="nav-link" href="{% url 'main:register' %}" style='color:white'
      style="font-family:Chelsea Market, cursive;'">Register</a>
    {% endif %}
  </div>
</nav>


{% endblock %}

traveller/main/templates/main/includes/notif.html
{% load static%}
{% block notif %}


    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script type=text/javascript>
                    toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": true,
                    "positionClass": "toast-top-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                    }
                toastr.success('{{ message }}')</script>
            {% elif message.tags == 'info' %}
                <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
            {% elif message.tags == 'warning' %}
                <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
            {% elif message.tags == 'error' %}
                <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock%}

traveller/main/templates/main/includes/notifications.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

traveller/main/templates/main/includes/postitem.html
{% load static%}
{% block postitem %}
<form action="{% url 'main:send_post'%}" method='POST'>
  {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4" name='city'>City</label>
      <input type="text" class="form-control" name='city' required='required'>
    </div>
    <div class="form-group col-md-6" >
      <label for="country" name="country">Country</label>
      <input type="text" class="form-control" name="country" required='required' value="{{name}}" readonly >
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="title" name='title'>Title</label>
      <input type="text" class="form-control" name='title' required='required'>
    </div>

  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="title" name='interest'>Interest</label>
      <input type="text" class="form-control" name='interest' required='required'>
    </div>
    <div class="form-group col-md-6">
      <label for="budget" name='budget'>Budget</label>
      <input type="text" class="form-control" name='budget' required='required'>
    </div>
  </div>
  <div class="form-group row">
    <label for="start" class="col-2 col-form-label" name='start'>Starts</label>
    <div class="col-10">
      <input class="form-control" type="date" name='start' value="2020-08-19" id="example-date-input">
    </div>
  </div>
  <div class="form-group row">
    <label for="end" class="col-2 col-form-label" name='end'>Ends</label>
    <div class="col-10">
      <input class="form-control" type="date" name='end' value="2020-08-19" id="example-date-input">
    </div>
  </div>
  <div class="form-row">
    
    <div class="form-group col-md-2 m-2">
      <label for="total">Traveler(s)</label>
      <input type="text" class="form-control" name="total" id="total" placeholder="1" required='required'>
    </div>
    <div class="form-group col-md-2  m-2">
      <label for="wanted">Expected</label>
      <input type="text" class="form-control" name="wanted" id="wanted" required='required'>
    </div>
    <div class="form-group col-md-2 m-2">
      <label for="free">Free</label>
      <input type="text" class="form-control" name="free" id="free" required='required'>
    </div>
  </div>
  <div class="form-group">
    <label for="message" name="message">Message</label>
    <textarea class="form-control" id="message" name="message" rows="3" required='required'></textarea>
  </div>


  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
  <button type="submit" class="btn btn-primary">Send post</button>

</form>
{% endblock %}

traveller/main/templates/main/includes/register-form.html
{% block content %}

{% load bootstrap4 %}
<header class="masthead">
  <div class="container h-100 mt-5">
    <div class="row h-100 align-items-center justify-content-center text-center">

      {# Display a form #}
      <div class='row justify-content-center'>
        <div class="col-12">
          <div class="card mb-3 ">
            <div class="card-body" style='width: 40vw;'>
              <form method="post" class="form" style="color: #343a40;">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-warning btn-block">submit</button>
                {% endbuttons %}
                Already have an account? <a href="/register"><strong>Login</strong></a>.
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</header>
{% endblock %}