traveller/main/urls.py
from django.urls import path
from . import views

app_name = "main"  # here for namespacing of urls.

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("register/", views.register, name="register"),
    path("account/", views.account, name="account"),
    path("posts/", views.posts, name="posts"),
    path("send_post/", views.send_post, name="send_post"),
    path("delete_post/", views.delete_post, name="delete_post"),
    path("send_message/", views.send_message, name="send_message"),
    path("modify_post/", views.modify_post, name="modify_post"),
    path("upload_img/", views.upload_img, name="upload_img"),
    path("messages_posted/", views.messages_posted, name="messages_posted"),
    path("display_map/", views.display_map, name="display_map"),
    path('update_account/', views.update_account, name="update_account"),
    path("get_geocode/", views.get_geocode, name="get_geocode"),
    path("profil/", views.profil, name="profil"),
    path("delete_message/<int:message_id>/", views.delete_message, name="delete_message")
]

traveller/traveller/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.conf.urls import handler404, handler500


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('realadmin/', admin.site.urls),
]

# handler404 = 'main.views.error_404_view'

# handler500 = 'main.views.error_500_view'

traveller/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Country(models.Model):
    """
    Class used to define a country
    """

    name = models.CharField(max_length=200)
    alpha_2 = models.CharField(max_length=20)
    alpha_3 = models.CharField(max_length=20)
    temp_averges = models.CharField(max_length=500)
    flag = models.CharField(max_length=200)
    resume = models.TextField()
    picture = models.TextField()


# Create your models here.
class Post(models.Model):
    """
    Class used to define a travel place
    """

    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    creation_date = models.DateField(auto_now=True)
    city = models.CharField(max_length=200)
    total_travelers = models.DecimalField(max_digits=4, decimal_places=0)
    wanted_travelers = models.DecimalField(max_digits=4, decimal_places=0)
    free_places = models.DecimalField(max_digits=4, decimal_places=0)
    interest = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    message = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    ready = models.BooleanField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    budget = models.CharField(max_length=100)


class UserAttributes(models.Model):
    """
    Class used to edit the user profil attributes
    """

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    avatar = models.CharField(max_length=100)
    last_connexion = models.DateField()
    about = models.TextField()
    img = models.TextField(default="")


class Messages(models.Model):
    """
    Class used to store messages send
    """

    title = models.CharField(max_length=200)
    created_at = models.DateField(auto_now=True)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)

traveller/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    """Form used for general query"""

    search = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "inputForm", "placeholder": "Ex: Paris"}
        ),
        label=False,
    )


class ProfilForm(forms.Form):
    """Form used for profil infos"""

    username = forms.CharField(max_length=100)
    about = forms.Textarea()


class UserFormWithEmail(UserCreationForm):
    """Class used to register with email"""

    email = forms.EmailField(required=True)
    age = forms.DecimalField(max_digits=2, min_value=18, decimal_places=0)

    def __init__(self, *args, **kwargs):
        super(UserFormWithEmail, self).__init__(*args, **kwargs)

        for fieldname in ["username", "email", "password1", "password2"]:
            self.fields[fieldname].help_text = None

    def save(self, commit=True):
        user = super(UserFormWithEmail, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class PostForm(forms.Form):
    """ Class used to define a post """

    country = forms.CharField(max_length=200)
    city = forms.CharField(max_length=200)
    total = forms.DecimalField(max_digits=4, decimal_places=0)
    wanted = forms.DecimalField(max_digits=4, decimal_places=0)
    free = forms.DecimalField(max_digits=4, decimal_places=0)
    interest = forms.CharField(max_length=200)
    title = forms.CharField(max_length=200)
    message = forms.CharField(max_length=2000)
    start = forms.CharField(max_length=200)
    end = forms.CharField(max_length=200)
    budget = forms.CharField(max_length=100)

    def save(self, commit=True):
        """Save method to insert posts in DB """

        country = self.country.cleaned_data["country"]
        city = self.city.cleaned_data["city"]
        total = self.total.cleaned_data["total"]
        wanted = self.wanted.cleaned_data["wanted"]
        free = self.free.cleaned_data["free"]
        interest = self.interest.cleaned_data["interest"]
        title = self.title.cleaned_data["title"]
        message = self.message.cleaned_data["message"]
        start = self.start.cleaned_data["start"]
        end = self.end.cleaned_data["end"]
        budget = self.budget.cleaned_data["budget"]

        return self.country

traveller/main/views.py
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import SearchForm
from django.views.decorators.csrf import requires_csrf_token, csrf_exempt
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserFormWithEmail, PostForm, ProfilForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.views import LoginView
from .geomap import GeoMaps
import pycountry
from main.models import Country, Post, Messages, UserAttributes
from django.http import JsonResponse
from datetime import date
from django.db.models import Count
from django.core.paginator import Paginator
from operator import itemgetter
import base64
from datetime import date, datetime
import os
import json


def index(request):
    """
    This function returns the  template
    """
    user = request.user
    month = datetime.now()
    month = month.strftime("%B")
    actual_month = month[0:3]

    mssg = Messages.objects.filter(author=user.id)
    choicelist = []
    c = Country.objects.all()
    for i in c:
        choicelist.append(i)

    post_count = Country.objects.annotate(Count("post"))

    clist = list(
        post_count.values_list(
            "name",
            "flag",
            "alpha_2",
            "post__count",
            "id",
            "resume",
            "picture",
            "temp_averges",            
        )
    )

    for i in range(0, len(clist)):
        clist[i] = list(clist[i])
        clist[i][-1] = json.dumps(eval(clist[i][-1]))

    clist = sorted(clist, key=itemgetter(3),)  # sort list by index[3] (posts)
    
    paginator = Paginator(clist, 6)  # Show  6  contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "actual_month": actual_month,
        "clist": clist,
        "choicelist": choicelist,
        "page_obj": page_obj,
        "mesages": mssg,
    }

    return render(request, "main/index.html", context)


def login_request(request):
    """
    This functions is used to get the user logged if
    the Auth is auth is success
    """
    if request.user.is_authenticated:
        return redirect("/")
    else:
        if request.method == "POST":
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(request, "Logged in!")
                    return redirect("/")
                else:
                    return redirect('/')
            else:
                pass
        form = AuthenticationForm()

        return render(
            request=request,
            template_name="main/login.html",
            context={"form": form},
        )


def register(request):
    """
    This function returns the register form template
    """
    if request.method == "POST":
        form = UserFormWithEmail(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get("username")
            login(request, user)
            today = date.today()
            user_att = UserAttributes(
                owner=user, avatar="", about="", img="", last_connexion=today
            )
            user_att.save()

            return redirect("/")
        else:
            return render(
                request=request,
                template_name="main/register.html",
                context={"form": form},
            )

    form = UserFormWithEmail
    return render(
        request=request,
        template_name="main/register.html",
        context={"form": form},
    )


def logout_request(request):
    """
    This function is used by the user to logout
    """
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "Logged out!")
        return redirect("main:index")
    else:
        return redirect("main:index")


def account(request):
    if request.user.is_authenticated:
        img = UserAttributes.objects.filter(owner=request.user).latest(
            "id"
        )
        img = img.img
        infos = UserAttributes.objects.filter(owner=request.user).latest("id")
        name = request.user.username
        email = request.user.email
        context = {"name": name, "email": email, "img": img, "infos": infos}
        return render(request, "main/account.html", context)
    else:
        return redirect("/")


def posts(request):
    if request.method == "GET":
        country_id = request.GET.get("country_id")
        api_key = os.environ.get("FRONT_API_KEY")
        clist = []
        c = Country.objects.all()
        for i in c:
            clist.append(i)
        try:
            c = Country.objects.get(id=country_id)
        except ValueError:
            return redirect("/")
        except ObjectDoesNotExist:
            return redirect("/")
        alpha = c.alpha_2
        name = c.name

        url = f"../static/img/flags/flag-{alpha}.jpg"
        user = request.user
        messages = Messages.objects.all()
        all_posts = Post.objects.filter(country__id=c.id)
        poster_pictures = {}
        for i in all_posts:
            user_instance = User.objects.get(username=i.created_by)
            try:
                user_attribut = UserAttributes.objects.filter(
                    owner=user_instance
                ).latest("id")
                poster_pictures[i.created_by] = user_attribut.img
            except:
                poster_pictures[i.created_by] = ""

        context = {
            "poster_pictures": poster_pictures,
            "messages": messages,
            "url": url,
            "user": user,
            "form": "form",
            "clist": clist,
            "name": name,
            "country_id": country_id,
            "all_posts": all_posts,
            "api_key": api_key,
        }

    return render(request, f"main/posts.html", context)


def send_post(request):
    if request.user.is_authenticated:
        form = PostForm(request.POST)
        if request.method == "POST":
            form = PostForm(request.POST)
            if form.is_valid():
                country = Country.objects.get(
                    name=form.cleaned_data["country"]
                )

                new_post = Post(
                    country=country,
                    city=form.cleaned_data["city"],
                    total_travelers=form.cleaned_data["total"],
                    wanted_travelers=form.cleaned_data["wanted"],
                    free_places=form.cleaned_data["free"],
                    interest=form.cleaned_data["interest"],
                    title=form.cleaned_data["title"],
                    message=form.cleaned_data["message"],
                    start_date=form.cleaned_data["start"],
                    end_date=form.cleaned_data["end"],
                    budget=form.cleaned_data["budget"],
                    ready=False,
                    created_by=request.user,
                )
                new_post.save()

                clist = []
                c = Country.objects.all()
                for i in c:
                    clist.append(i)
                all_posts = Post.objects.filter(country__id=country.id)
                alpha = country.alpha_2
                url = f"../static/img/flags/flag-{alpha}.jpg"
                name = country.name
                mess = "Message sent!"
                context = {
                    "all_posts": all_posts,
                    "clist": clist,
                    "url": url,
                    "name": name,
                    "mess": mess,
                }
                messages.success(request, "Post sent!")
                return render(request, "main/posts.html", context)
            else:
                return redirect("/")
        else:
            return redirect("/")
    else:
        return render(request, "main/posts.html")


@requires_csrf_token
def delete_post(request) -> dict:
    if request.user.is_authenticated:
        try:
            post_id = request.POST["post_id"]
            selected_post = Post.objects.get(id=post_id)
            selected_post.delete()
            return JsonResponse({"result": "deleted"})
        except ValueError:
            return JsonResponse({"result": "failed"})
    else:
        return redirect("/")


@requires_csrf_token
def send_message(request) -> dict:
    """
    Function used to send message
    """
    if request.user.is_authenticated:        
        content = request.POST.get("message")
        author = request.user
        post_ref = request.POST.get("post_ref")
        post_id = Post.objects.get(id=post_ref)
        Messages.objects.create(
            title="", content=content, author=author, post_id=post_id
        )
        return JsonResponse({"message": "SEND OK"})
    return JsonResponse({"failed": "failed"})


@requires_csrf_token
def modify_post(request) -> dict:
    """
    Function defined to modify a specific post
    """
    if request.user.is_authenticated:
        if request.is_ajax():
            post_id = request.POST["post_id"]
            post = Post.objects.filter(id=post_id).values()
            post = post[0]

            context = {
                "post": post,
            }
            return JsonResponse(context)
    else:
        return redirect("/")


@requires_csrf_token
def upload_img(request) -> dict:
    """
    Function defined to upload profile image
    """

traveller/main/templates/main/account.html
<!DOCTYPE html>
<html>
{% load static %} {% load crispy_forms_tags%}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.png">
    <title>Travelerer</title>
    <!-- Latest compiled and minified CSS -->

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '/css/account.css'%}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Antone">
    <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">


</head>

<body>
    {% comment %} START BG IMG {% endcomment %}
    {% comment %} <div
        style="background: linear-gradient(rgba(119, 119, 119, 0.5),rgba(60, 66, 68, 0.5)),  url('../../static/img/account-bg.jpg')"
        class="page-holder bg-cover"> {% endcomment %}


        {% comment %} NAVBAR {% endcomment %}
        {% block content %}
        {% include './includes/navbar.html' %}
        {% endblock content %}
        {% comment %} END NAVBAR {% endcomment %}





        {% comment %} PROFILE CONTENT {% endcomment %}
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <div class="container ">
            <div class="row flex-lg-nowrap">
                <div class="col-12 col-lg-auto mb-3" style="width: 200px;">
                </div>
                <div class="col mt-5">
                    <div class="row">
                        <div class="col mb-3">
                            <div class="card">
                                <div class="card-body account-box">
                                    <div class="e-profile">
                                        <div class="row">
                                            <div class="col-12 col-sm-auto mb-3">
                                                <div class="mx-auto" style="width: 140px;">
                                                    <div class="d-flex justify-content-center align-items-center rounded"
                                                        style="height: 140px; background-color: rgb(233, 236, 239);">
                                                        {% if img %}
                                                        <div class='preview'>
                                                            <img src="{{img}}" id="profile-img" width="100"
                                                                height="100">
                                                        </div>
                                                        {% else %}
                                                        <span
                                                            style="color: rgb(166, 168, 170); font: bold 8pt Arial;">140x140</span>
                                                        {% endif%}
                                                    </div>
                                                </div>
                                            </div>
                                            <div
                                                class="col d-flex flex-column flex-sm-row justify-content-between mb-3">
                                                <div class="text-center text-sm-left mb-2 mb-sm-0">
                                                    <h4 class="pt-sm-2 pb-1 mb-0 text-nowrap">{{name}}</h4>
                                                    <p class="mb-0">{{email}}</p>
                                                    <div class="text-muted"><small>Last seen 2 hours ago</small></div>
                                                    <div class="container">
                                                        <form method="post" action="" enctype="multipart/form-data"
                                                            id="myform">                                                            <div>
                                                                <input type="file" id="file" name="file" />
                                                                <input type="button" class="btn btn-primary button" value="Upload image "
                                                                    name="upload-img" id="but_upload">
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                                <div class="text-center text-sm-right">
                                                    <span class="badge badge-secondary">administration</span>
                                                </div>
                                            </div>
                                        </div>
                                        <ul class="nav nav-tabs">
                                            <li class="nav-item"><a href="" class="active nav-link">Settings</a></li>
                                        </ul>
                                        <div class="tab-content pt-3">
                                            <div class="tab-pane active">
                                                <form class="form" action="{% url 'main:update_account'%}" method="POST">
                                                {% csrf_token %}
                                                     {{form}}
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="row">
                                                                <div class="col">
                                                                    <div class="form-group">                                                                        
                                                                        <input class="form-control" type="text"
                                                                            name="username" placeholder="{{infos.owner.username}}"
                                                                            value="{{infos.owner.username}}" required='required'>
                                                                    </div>
                                                                </div>
                                                            </div>                                                            
                                                            <div class="row">
                                                                <div class="col mb-3">
                                                                    <div class="form-group">
                                                                        <textarea class="form-control" rows="5"
                                                                          placeholder="{{infos.about}}" name="about"   required='required'  ></textarea>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col d-flex justify-content-end">
                                                            <button class="btn btn-primary" type="submit">Save
                                                                Changes</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-12 col-md-3 mb-3">


                        </div>
                    </div>

                </div>
            </div>
        </div>

        {% comment %} END PROFILE CONTENT {% endcomment %}

        {% comment %} END IMAGE BACKGROUND {% endcomment %}
        {% comment %}
    </div> {% endcomment %}

    {% comment %} LINKS {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static '/js/account.js'%}"></script>

    {% comment %} END LINKS {% endcomment %}
</body>

</html>

traveller/main/templates/main/login.html
<!DOCTYPE html>
<html>
{% load static %} {% load crispy_forms_tags%}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.png">
    <title>Travelerer</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '/css/index.css'%}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Antone">
        <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">


</head>

<body>
    {% comment %} START BG IMG {% endcomment %}
    <div style="background: url('../../static/img/background-register.jpeg')"
        class="page-holder bg-cover">


        {% comment %} NAVBAR {% endcomment %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Travelerer Helper</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                </ul>
                <a class="nav-link" href="{% url 'main:register'%}" style='color:white'>Register</a>


            </div>
        </nav>

        {% comment %} END NAVBAR {% endcomment %}


        {% comment %} FORM {% endcomment %}
        {% block content %}
            {% include './includes/login-form.html' %}
        {% endblock %}
        {% comment %} END FORM {% endcomment %}



        {% comment %} END BG IMAGE {% endcomment %}
    </div>







    {% comment %} FOOTER {% endcomment %}



    {% comment %} END FOOTER {% endcomment %}






    {% comment %} LINKS {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static '/js/index.js'%}"></script>

    {% comment %} END LINKS {% endcomment %}
</body>

</html>